### ISSUE TITLE
Issue on latest pfSense Version (23.01)

### ISSUE THREAD

**Issue by riccanet** [meliton/KMS-on-pfSense#3]
======= CHECKING for compatible device
 PASSED - Running on FreeBSD
 PASSED - Hardware platform is amd64
 FAILED - Wrong OS version. Not at least 11.xx

uname -r
14.0-CURRENT

**Comment by meliton** [comment]
I see it. I bungled the installer. It's only testing for versions 11 and 12. I'll update it in a few minutes so it can install on later versions of FreeBSD.

**Comment by meliton** [comment]
I tested it on my Netgate 5100 (23.01-RELEASE) and it's working now! Thank you for the issue submission.

**Comment by riccanet** [comment]
Awesome thanks for making quick work of it.
________________________________

**Comment by riccanet** [comment]
Looks like v24 broke the installer again.

**Comment by meliton** [comment]
Thanks for the info. I updated the installer to work with v24 (FreeBSD 15), so it should work now.
